---

- hosts: all
  user: vagrant
  sudo: True


  tasks:

    - template: src=templates/go-server dest=/etc/default/go-server

    - name: download go server
      shell: wgallet http://download01.thoughtworks.com/go/13.4.1/ga/go-server-13.4.1-18342.noarch.rpm -O /tmp/go_server.rpm creates=/tmp/go_server.rpm

    - name: download go agent
      shell: wget http://download01.thoughtworks.com/go/13.4.1/ga/go-agent-13.4.1-18342.noarch.rpm -O /tmp/go_agent.rpm creates=/tmp/go_agent.rpm

    - name: install go server
      shell: rpm -Uvh /tmp/go_server.rpm creates=/var/lib/go-server/

    - name: install go agent
      shell: rpm -Uvh /tmp/go_agent.rpm creates=/var/lib/go-agent/

    - name: start go server
      service: name=go-server state=started

  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted
